version: "3"
   
services:
  web:
    container_name: DjangoProject
    build: 
        context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    networks:
      - DjangoNetwork_dev
networks:
  DjangoNetwork_dev:
    external:
      name: DjangoNetwork_dev