# Generated by Django 3.2.6 on 2021-08-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_adressentery_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressentery',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FAMELE', 'Famele')], max_length=9, null=True),
        ),
    ]
