# Generated by Django 3.2.6 on 2021-08-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_adressentery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressentery',
            name='user',
        ),
    ]
