# Generated by Django 3.2.6 on 2021-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210903_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressentery',
            name='firstName',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='adressentery',
            name='lastName',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='adressentery',
            name='phoneNumber',
            field=models.IntegerField(default=None),
        ),
    ]
