# Generated by Django 3.2.6 on 2021-09-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteentery',
            old_name='timer',
            new_name='date',
        ),
        migrations.AddField(
            model_name='noteentery',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
